# Single Dimension Numpy Array

In [8]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [14]:
type(n1)

numpy.ndarray

In [12]:
n1=np.arange(5,10)
n1

array([5, 6, 7, 8, 9])

In [16]:
type(n1)

numpy.ndarray

# MultiDimension array

In [21]:
n2=np.array([[10,20,30],[10,80,90],[30,40,50]])
n2

array([[10, 20, 30],
       [10, 80, 90],
       [30, 40, 50]])

In [24]:
n2.shape

(3, 3)

# initialze of numpy array with zeros

In [29]:
n3=np.zeros((11,11))
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# initailize a array with full

In [34]:
n4=np.full((11,11),13)
n4

array([[13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13]])

# with in a arange

In [41]:
n5=np.arange(10,20)

In [39]:
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
n5=np.arange(10,19).reshape(3,3)

In [45]:
n5

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# initialization with the skip numbers 

In [48]:
n6=np.arange(1,10,2)

In [50]:
n6

array([1, 3, 5, 7, 9])

# with the random numbers

In [55]:
n7=np.random.randint(100,100000,10)
n7

array([90166,  2026, 94122, 62071, 69946, 57289, 90378, 15368, 51993,
       81329])

# joining numpy array

In [58]:
a=np.arange(10,20)
b=np.arange(20,30)
c=np.arange(30,40)
d=np.arange(40,50)
e=np.arange(50,60)

In [62]:
np.vstack((a,b,c,d,e))

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [66]:
np.hstack((a,b,c,d,e))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [68]:
np.column_stack((a,b,c,d,e))

array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52],
       [13, 23, 33, 43, 53],
       [14, 24, 34, 44, 54],
       [15, 25, 35, 45, 55],
       [16, 26, 36, 46, 56],
       [17, 27, 37, 47, 57],
       [18, 28, 38, 48, 58],
       [19, 29, 39, 49, 59]])

# numpy intersection and differences

In [79]:
x=np.arange(10,20)
y=np.arange(20,30)

In [81]:
np.intersect1d(x,y)

array([], dtype=int32)

In [83]:
np.setdiff1d(x,y)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [87]:
np.union1d(x,y)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

# Addition of the numpy array

In [92]:
t=np.array([10,20])
s=np.array([20,30])

In [94]:
np.sum([t,s])

80

In [96]:
np.sum([t,s],axis=0)

array([30, 50])

In [98]:
np.sum([t,s],axis=1)

array([30, 50])

# Numpy Array Mathematics

In [101]:
p=np.array([10,20,30])
p+p

array([20, 40, 60])

In [103]:
p**p

array([1410065408,          0, 1073741824])

In [105]:
p-p

array([0, 0, 0])

In [107]:
p+1

array([11, 21, 31])

In [109]:
p-1

array([ 9, 19, 29])

In [111]:
p/p

array([1., 1., 1.])

# Numpy Math functions

In [120]:
nn=np.arange(10,60,10)

In [122]:
nn

array([10, 20, 30, 40, 50])

In [124]:
np.mean(nn)

30.0

In [126]:
np.median(nn)

30.0

In [128]:
np.std(nn)

14.142135623730951

In [136]:
np.quantile(nn,0.50) # 0.50 is the 2nd quartile 

30.0

In [138]:
np.var(nn)

200.0

In [140]:
np.cov(nn)

array(250.)

In [142]:
np.max(nn)

50

In [144]:
np.min(nn)

10

# saving and loading numpy array

In [151]:
n11=np.arange(10,20,3)

In [153]:
np.save("my_name",n11)# Saving the numpy array

In [157]:
np.load('my_name.npy')

array([10, 13, 16, 19])

# Identity vs eye

In [162]:
np.identity(4) 


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [164]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Einisten Summation conveition method
- 

### This function is used to compute many multidimensional and linear algebraric operations on array

In [179]:
a=np.arange(21,30,1)
a

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [181]:
b=np.arange(1,10,1)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
a=np.arange(21,30,1).reshape(3,3)
a

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [189]:
b=np.arange(1,10,1).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [201]:
## to extract the diagonal of 
print(np.diag(a))

[21 25 29]


In [191]:
np.einsum('ij->ji',a)  # for the transpose 

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [197]:
print(np.linalg.det(a)) # to find the determinant 

0.0


In [199]:
print(np.linalg.det(b))

0.0


In [203]:
# Matrix Multiplication
np.einsum('ij,jk',a,b)

array([[270, 336, 402],
       [306, 381, 456],
       [342, 426, 510]])

# Matrix and Vector Multiplication


In [208]:
A=np.array([[1,2],[3,4],[5,6]])
x=np.array([7,8])
print(np.einsum('ij,j->i',A,x))

[23 53 83]
